### ISSUE TITLE
[Question] Is this still an active project?

### ISSUE THREAD

**Issue by trsh** [MathisWellmann/gym-rs#2]

**Comment by MathisWellmann** [comment]
Yes it's active. Feel free to contribute to make it even better

**Comment by trsh** [comment]
Hmm. Not so much updates recently :)

**Comment by MathisWellmann** [comment]
Haha, true. I got a lot of other important projects to work on and gym-rs is at a stage where all the basics are implemented and working correctly. There are however some outstanding todos, some are easy as well. So if you require some more features for your own project don't hesitate to implement them :D

**Comment by trsh** [comment]
If the basics are implemented why does the readme say Alarm! Wip!?
