### ISSUE TITLE
Cartpole enviorment can start in an unrecoverable state. 

### ISSUE THREAD

**Issue by aDecoy** [MathisWellmann/gym-rs#7]
Hi, i am using gym-rs to learn rust by making a genetic algorithm to balance a stick. Your stick ;) 

A lot of simulations seems to end after the first action. After some debugging i found that the init state can be already beyond what makes it "done".  I think the init state needs to be changed to land inside the "not done space". I am very new to rust, so i dont have a solution to post. But i think it should be an easy fix. ... i hope. 

Debugging code and result:
```

    let mut init_observation: CartPoleObservation = env.reset(None, false, None).0;
    println!("---------------------");
    println!("env.x_threshold {}", env.x_threshold);
    println!("env.theta_threshold_radians {}", env.theta_threshold_radians);
    println!("init_observation {:?}", Vec::from(init_observation));
    println!("---------------------");

```
Prints the following: 
```
env.x_threshold 2.4
env.theta_threshold_radians 0.20943951023931953
init_observation [0.012382612957275718, 0.014833725476475657, -0.3528077663467408, 0.3304920176194186]
```

PS/Note: the print might be impacted by me changing a small detail that i suspect was a bug. 

```
        self.state = CartPoleObservation {
            x,
            x_dot,
            theta_dot,
            theta,
        };

```
to

```
        self.state = CartPoleObservation {
            x,
            x_dot,
            theta,
            theta_dot,
        };
        
```

**Comment by aDecoy** [comment]
Think i got a simple solution. Need to use theta_threshold_radians in sample_between default. Dont know how to use the value there in a propper rusty way, so i did the most easy thing

fn sample_between<R: Rng>(rng: &mut R, bounds: Option<BoxR<Self>>) -> Self {
        let BoxR { low, high } = bounds.unwrap_or({
            let observation_bound = CartPoleObservation::new(
                OrderedFloat(0.5),
                OrderedFloat(0.5),
                OrderedFloat(12. * 2. * PI / 360.),
                OrderedFloat(0.5),
            );
            BoxR::new(-observation_bound, observation_bound)
        });
        Uniform::new(low, high).sample(rng)

**Comment by MathisWellmann** [comment]
Thanks for pointing this out. I will investigate and fix this today

**Comment by aDecoy** [comment]
Cool 👍 Glad to see you were on it so quick. Sorry for late feedback. Hope my aid helped :)
